---
title: "Obtenção dos dados do Fundeb"
author: "Henrique de Assunção"
date: "2024-02-04"
output: html_document
---

# Obtenção dos dados

> Todos os dados foram baixados no dia 04/02/2024, para atualizar os valores para outros momentos é necessário se fazer a mudança dos respectivos endereços para as suas versões mais atualizadas.

Os dados do Fundeb no site do governo do fundo. Como vamos trabalhar com os dados mais recentes do Fundeb, baixamos os dados de 2024 no [portal do fundeb](https://www.gov.br/fnde/pt-br/acesso-a-informacao/acoes-e-programas/financiamento/fundeb/consultas). Precisamos dos dados de matrículas, de recursos do Fundeb do ano, recursos do Fundeb de dois anos atrás (VAAT) e pesos da complementação VAAR, de habilitação dos entes (VAAT e VAAR), de pesos das matrículas e de nível socioeconômico. Os dados podem ser obtidos nos seguintes links:

* [Matrículas](https://www.gov.br/fnde/pt-br/acesso-a-informacao/acoes-e-programas/financiamento/fundeb/matriculas-da-educacao-basica/2024-com-base-na-portaria-interministerial-no-6-de-28-12-2023): Matrículas por etapa e por estado, necessário baixar estado por estado;
* [Recursos do Fundeb atual](https://www.gov.br/fnde/pt-br/acesso-a-informacao/acoes-e-programas/financiamento/fundeb/2024/ReceitaeComplementaoporentefederadoFundebVAAF2024.pdf): recursos considerados para a complementação VAAF;
* [Fundeb de dois anos atrás (VAAT)](https://www.gov.br/fnde/pt-br/acesso-a-informacao/acoes-e-programas/financiamento/fundeb/2024/ReceitaSTN2022VAAT2024parapublicao.pdf): recursos de dois anos atrás usados para o cálculo da complementação VAAT;
* [Peso VAAR](https://www.gov.br/fnde/pt-br/acesso-a-informacao/acoes-e-programas/financiamento/fundeb/2024-1): Pesos de cada ente na complementação VAAR;
* [Habilitação VAAT](https://www.gov.br/fnde/pt-br/acesso-a-informacao/acoes-e-programas/financiamento/fundeb/ListafinalhabilitaoVAAT202431agosto2023.pdf): redes inabilitadas na complementação VAAT;
* [Habilitação VAAR](https://www.gov.br/fnde/pt-br/acesso-a-informacao/acoes-e-programas/financiamento/fundeb/2024/Redesinabilitadaspormotivo.pdf): redes inabilitadas na complementação VAAR;
* [Peso das matrículas](https://www.gov.br/fnde/pt-br/acesso-a-informacao/acoes-e-programas/financiamento/fundeb/2024/FatoresdeponderaoFundeb2024.pdf): peso das matrículas por tipo de ensino em cada uma das etapas;
* [Nível socioeconômico (NSE)](https://www.gov.br/fnde/pt-br/acesso-a-informacao/acoes-e-programas/financiamento/fundeb/2024/PonderadorNSE.pdf): Nível socioeconômico por ente, usado na ponderação das matrículas;
* [Matrículas](https://www.gov.br/fnde/pt-br/acesso-a-informacao/acoes-e-programas/financiamento/fundeb/matriculas-da-educacao-basica-1): Matrículas por etapa para cada ente;

Observação, os dados de recursos, pesos, habilitação para complementação e nível socioeconômico estão na página do [Fundeb mais atual](https://www.gov.br/fnde/pt-br/acesso-a-informacao/acoes-e-programas/financiamento/fundeb/2024-1) acessada na página de consulta do página do fundeb.

Os dados são baixados em formato PDF e então transformados em xlsx, usando-se aum script em python para os dados de matrículas e a plataforma [ilovepdf](https://www.ilovepdf.com/) para todos os outros dados. O script encontra-se no repositório deste projeto.
